fix(src): memoize resolver import
Fixes an issue where testApiHandler would either never resolve or throw
a "v is not a function" TypeError due to subsequent imports of the
api resolver failing for whatever reason. Memoizing the resolver
upon initial import fixes this problem across all tested versions of
Next.js!